myData = read.table("household_power_consumption.txt",header = T,sep = ';')
head(myData)
date1 <- as.Date("2007-02-01",format = "%Y-%m-%d")
date2 <- as.Date("2007-02-02",format = "%Y-%m-%d")
myData <- transform(myData,Date = as.Date(Date,format = "%d/%m/%Y"))
relevantData <- myData[myData$Date==date1 | myData$Date==date2,]
relevantData <- transform(relevantData,Time = strptime(paste(Date,Time),format = "%Y-%m-%d %H:%M:%S"))
relevantData <- transform(relevantData,Sub_metering_1 = as.numeric(as.character(Sub_metering_1)))
relevantData <- transform(relevantData,Sub_metering_2 = as.numeric(as.character(Sub_metering_2)))
relevantData <- transform(relevantData,Sub_metering_3 = as.numeric(as.character(Sub_metering_3)))
plot(relevantData$Time,relevantData$Sub_metering_1,type = 'l',col = 'black',ylab = "Energy sub metering",xlab = "",ylim = range(relevantData$Sub_metering_1,relevantData$Sub_metering_2,relevantData$Sub_metering_3))
points(relevantData$Time,relevantData$Sub_metering_2,col = 'red',type = 'l')
points(relevantData$Time,relevantData$Sub_metering_3,col = 'blue',type = 'l')
legend("topright",legend= c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty = 1,col = c("black",'red','green'))
dev.copy(png,file = 'plot3.png',width = 480,height = 480,units = 'px')
dev.off()